# Generated by Django 4.0.5 on 2022-06-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='published',
        ),
    ]
